=== janka95/ModernDB/SemTasks/XQuery/GIE0EJ_ovoda.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="ovoda">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="csoport" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="dolgozo" maxOccurs="unbounded">
                			<xs:complexType>
                   				 <xs:sequence>
                       				<xs:element name="nev" type="xs:string"/>
                       				<xs:element name="beosztas" type="xs:string"/>
                        			<xs:element name="szulido" type="xs:integer"/>
                   				 </xs:sequence>
                    			<xs:attribute type="xs:integer" name="id" use="required"/>
                			</xs:complexType>
           				</xs:element>
           				<xs:element name="gyerek" maxOccurs="unbounded">
                			<xs:complexType>
                   				 <xs:sequence>
                       				<xs:element name="nev" type="xs:string"/>
                        			<xs:element name="szulido" type="xs:integer"/>
                   				 </xs:sequence>
                    			<xs:attribute type="xs:string" name="jel" use="required"/>
                			</xs:complexType>
           				</xs:element>
                    </xs:sequence>
                    <xs:attribute type="xs:string" name="nev" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== janka95/ModernDB/GIE0EJ_0425/GIE0EJ_ovoda.xml
<ovoda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="GIE0EJ_ovoda.xsd">
	<csoport nev="süni">
		<dolgozo id="1">
			<nev>Kiss Júlia</nev>
			<beosztas>óvónő</beosztas>
			<szulido>1989</szulido>
		</dolgozo>
		<dolgozo id="2">
			<nev>Nagy Mária</nev>
			<beosztas>dajka</beosztas>
			<szulido>1965</szulido>		
		</dolgozo>
		<gyerek jel="alma">
			<nev>Szabó Péter</nev>
			<szulido>2020</szulido>
		</gyerek>
		<gyerek jel="körte">
			<nev>Okos Tóni</nev>
			<szulido>2019</szulido>
		</gyerek>	
		<gyerek jel="virág">
			<nev>Kovács Márta</nev>
			<szulido>2019</szulido>
		</gyerek>						
    </csoport>
		<csoport nev="maci">
		<dolgozo id="3">
			<nev>Gipsz Jolán</nev>
			<beosztas>óvónő</beosztas>
			<szulido>1980</szulido>
		</dolgozo>
		<dolgozo id="4">
			<nev>Szép Etelka</nev>
			<beosztas>dajka</beosztas>
			<szulido>1968</szulido>		
		</dolgozo>
		<gyerek jel="alma">
			<nev>Kiss Tamás</nev>
			<szulido>2018</szulido>
		</gyerek>
		<gyerek jel="kocsi">
			<nev>Nagy Zoltán</nev>
			<szulido>2019</szulido>
		</gyerek>
		<gyerek jel="szilva">
			<nev>Takács Lili</nev>
			<szulido>2019</szulido>
		</gyerek>						
	</csoport>
		<csoport nev="napocska">
		<dolgozo id="5">
			<nev>Varga Móni</nev>
			<beosztas>óvónő</beosztas>
			<szulido>1983</szulido>
		</dolgozo>
		<dolgozo id="6">
			<nev>Pásztor Erzsi</nev>
			<beosztas>dajka</beosztas>
			<szulido>1975</szulido>		
		</dolgozo>
		<gyerek jel="dominó">
			<nev>Szabó Virág</nev>
			<szulido>2018</szulido>
		</gyerek>
		<gyerek jel="csillag">
			<nev>Teszt Elek</nev>
			<szulido>2019</szulido>
		</gyerek>
		<gyerek jel="alma">
			<nev>Horváth Sára</nev>
			<szulido>2019</szulido>
		</gyerek>						
	</csoport>	
</ovoda>
