=== janka95/ModernDB/SemTasks/XML/DOMParseGIE0EJ/src/XMLSchemaGIE0EJ.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified"
attributeFormDefault="qualified">

<xs:element name="kapukod" type="xs:integer"/>
<xs:element name="ir_szam" type="xs:integer"/>
<xs:element name="telepules" type="xs:string"/>
<xs:element name="utca_hazszam" type="xs:string"/>
<xs:element name="agynemu" type="xs:string"/>
<xs:element name="idopont" type="xs:date"/>
<xs:element name="nev" type="xs:string"/>
<xs:element name="szem_ig_szam" type="xs:string"/>
<xs:element name="mobilszam" type="xs:string"/>
<xs:element name="k_datum" type="xs:date"/>
<xs:element name="z_datum" type="xs:date"/>
<xs:element name="fo" type="xs:integer"/>
<xs:element name="utlevel_sz" type="xs:string"/>
<xs:element name="telefonszam" type="xs:string"/>

<xs:attribute name="lakas_ID" type="xs:integer"/>
<xs:attribute name="takarito_ID" type="xs:integer"/>
<xs:attribute name="lakas_IDREF" type="xs:integer"/>
<xs:attribute name="takarito_IDREF" type="xs:integer"/>
<xs:attribute name="foglalas_ID" type="xs:integer"/>
<xs:attribute name="vendeg_IDREF" type="xs:integer"/>
<xs:attribute name="vendeg_ID" type="xs:integer"/>

<xs:complexType name="cim_tipus">
	<xs:sequence>
		<xs:element ref="ir_szam"/>
		<xs:element ref="telepules"/>
		<xs:element ref="utca_hazszam"/>
	</xs:sequence>
</xs:complexType>



<xs:complexType name="lakasok_tipus">
	<xs:sequence>
		<xs:element name="lakas" type="lakas_tipus" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="takaritasok_tipus">
	<xs:sequence>
		<xs:element name="takaritas" type="takaritas_tipus" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="takaritok_tipus">
	<xs:sequence>
		<xs:element name="takarito" type="takarito_tipus" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="foglalasok_tipus">
	<xs:sequence>
		<xs:element name="foglalas" type="foglalas_tipus" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="vendegek_tipus">
	<xs:sequence>
		<xs:element name="vendeg" type="vendeg_tipus" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="vendeg_tipus">
	<xs:sequence>
		<xs:element ref="nev"/>
		<xs:element ref="telefonszam" maxOccurs="unbounded"  />
		<xs:element ref="utlevel_sz"/>
	</xs:sequence>
	<xs:attribute ref="vendeg_ID" use="required"/>	
</xs:complexType>

<xs:complexType name="foglalas_tipus">
	<xs:sequence>
		<xs:element ref="k_datum" />
		<xs:element ref="z_datum" />
		<xs:element ref="fo" />
	</xs:sequence>
	<xs:attribute ref="foglalas_ID" use="required"/>
	<xs:attribute ref="lakas_IDREF" use="required"/>
	<xs:attribute ref="takarito_IDREF" use="required"/>
	<xs:attribute ref="vendeg_IDREF" use="required"/>
</xs:complexType>

<xs:complexType name="takarito_tipus">
	<xs:sequence>
		<xs:element ref="nev" />
		<xs:element ref="szem_ig_szam" />
		<xs:element ref="mobilszam" />
	</xs:sequence>
	<xs:attribute ref="takarito_ID" use="required"/>
</xs:complexType>

<xs:complexType name="takaritas_tipus">
	<xs:sequence>
		<xs:element ref="idopont" />
	</xs:sequence>
	<xs:attribute ref="takarito_IDREF" use="required"/>
	<xs:attribute ref="lakas_IDREF" use="required"/>
</xs:complexType>

<xs:complexType name="lakas_tipus">
	<xs:sequence>
		<xs:element ref="kapukod" />
		<xs:element name="cim" type="cim_tipus" />
		<xs:element ref="agynemu" />
	</xs:sequence>
	<xs:attribute ref="lakas_ID" use="required"/>
</xs:complexType>


<xs:element name="airbnblakasoktakaritasa">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="lakasok" type="lakasok_tipus"/>
			<xs:element name="takaritasok" type="takaritasok_tipus"/>
			<xs:element name="takaritok" type="takaritok_tipus"/>
			<xs:element name="foglalasok" type="foglalasok_tipus"/>
			<xs:element name="vendegek" type="vendegek_tipus"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:key name="lakas_PK">
		<xs:selector xpath="lakasok/lakas"/>
		<xs:field xpath="@lakas_ID"/>
	</xs:key>
	<xs:key name="takarito_PK">
		<xs:selector xpath="takaritok/takarito"/>
		<xs:field xpath="@takarito_ID"/>
	</xs:key>
	<xs:key name="foglalas_PK">
		<xs:selector xpath="foglalasok/foglalas"/>
		<xs:field xpath="@foglalas_ID"/>
	</xs:key>
	<xs:key name="vendeg_PK">
		<xs:selector xpath="vendegek/vendeg"/>
		<xs:field xpath="@vendeg_ID"/>
	</xs:key>
	
	<xs:keyref name="t_lakas_FK" refer="lakas_PK">
		<xs:selector xpath="takaritasok/takaritas"/>
		<xs:field xpath="@lakas_IDREF"/>
	</xs:keyref>
	<xs:keyref name="t_takarito_FK" refer="takarito_PK">
		<xs:selector xpath="takaritasok/takaritas"/>
		<xs:field xpath="@takarito_IDREF"/>
	</xs:keyref>
	<xs:keyref name="f_lakas_FK" refer="lakas_PK">
		<xs:selector xpath="foglalasok/foglalas"/>
		<xs:field xpath="@lakas_IDREF"/>
	</xs:keyref>
	<xs:keyref name="f_takarito_FK" refer="takarito_PK">
		<xs:selector xpath="foglalasok/foglalas"/>
		<xs:field xpath="@takarito_IDREF"/>
	</xs:keyref>
	<xs:keyref name="vendeg_FK" refer="vendeg_PK">
		<xs:selector xpath="foglalasok/foglalas"/>
		<xs:field xpath="@vendeg_IDREF"/>
	</xs:keyref>
</xs:element> 
</xs:schema>

=== janka95/ModernDB/SemTasks/XML/XMLGIE0EJ.xml
<?xml version="1.0" encoding="UTF-8"?>

<airbnblakasoktakaritasa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemaGIE0EJ.xsd">
	<lakasok>
		<lakas lakas_ID="1">
			<kapukod>2345</kapukod>
			<cim>
				<ir_szam>1065</ir_szam>
				<telepules>Budapest</telepules>
				<utca_hazszam>Révay utca 8</utca_hazszam>
			</cim>
			<agynemu>szimpla</agynemu>
		</lakas>
		<lakas lakas_ID="2">
			<kapukod>3456</kapukod>
			<cim>
				<ir_szam>1061</ir_szam>
				<telepules>Budapest</telepules>
				<utca_hazszam>Andrássy út 23</utca_hazszam>
			</cim>
			<agynemu>dupla</agynemu>
		</lakas>
		<lakas lakas_ID="3">
			<kapukod>4585</kapukod>
			<cim>
				<ir_szam>1051</ir_szam>
				<telepules>Budapest</telepules>
				<utca_hazszam>Zrínyi utca 4</utca_hazszam>
			</cim>
			<agynemu>szimpla</agynemu>
		</lakas>
	</lakasok>
	<takaritasok>
		<takaritas lakas_IDREF="1" takarito_IDREF="3">
			<idopont>2021-12-01</idopont>
		</takaritas >
		<takaritas lakas_IDREF="3" takarito_IDREF="2">
			<idopont>2021-12-04</idopont>
		</takaritas >
		<takaritas lakas_IDREF="2" takarito_IDREF="1">
			<idopont>2021-12-06</idopont>
		</takaritas >
	</takaritasok>
	<takaritok>
		<takarito takarito_ID="1">
			<nev>Kiss Mária</nev>
			<szem_ig_szam>231456PA</szem_ig_szam>
			<mobilszam>06308573245</mobilszam>
		</takarito>
		<takarito takarito_ID="2">
			<nev>Nagy Katalin</nev>
			<szem_ig_szam>463782EE</szem_ig_szam>
			<mobilszam>06204563998</mobilszam>
		</takarito>
		<takarito takarito_ID="3">
			<nev>Szabó Péter</nev>
			<szem_ig_szam>125478LD</szem_ig_szam>
			<mobilszam>06703456787</mobilszam>
		</takarito>
	</takaritok>
	<foglalasok>
		<foglalas foglalas_ID="1" lakas_IDREF="1" takarito_IDREF="3"  vendeg_IDREF="1">
			<k_datum>2021-11-29</k_datum>
			<z_datum>2021-12-01</z_datum>
			<fo>3</fo>
		</foglalas>
		<foglalas foglalas_ID="2" lakas_IDREF="3" takarito_IDREF="2"  vendeg_IDREF="2">
			<k_datum>2021-12-03</k_datum>
			<z_datum>2021-12-04</z_datum>
			<fo>2</fo>
		</foglalas>
		<foglalas foglalas_ID="3" lakas_IDREF="2" takarito_IDREF="1"  vendeg_IDREF="3">
			<k_datum>2021-12-04</k_datum>
			<z_datum>2021-12-06</z_datum>
			<fo>2</fo>
		</foglalas>
	</foglalasok>
	<vendegek>
		<vendeg vendeg_ID="1">
			<nev>John Smith</nev>
			<telefonszam>+223456785</telefonszam>
			<telefonszam>06304567855</telefonszam>
			<utlevel_sz>234567AA</utlevel_sz>
		</vendeg>
		<vendeg vendeg_ID="2">
			<nev>Nagy Tamás</nev>
			<telefonszam>06702874956</telefonszam>
			<utlevel_sz>475839BD</utlevel_sz>
		</vendeg>
		<vendeg vendeg_ID="3">
			<nev>Kovács Piroska</nev>
			<telefonszam>06303455443</telefonszam>
			<telefonszam>061223678</telefonszam>
			<utlevel_sz>347656PL</utlevel_sz>
		</vendeg>
	</vendegek>
</airbnblakasoktakaritasa>
